In [1]:
import cv2
import os
import numpy as np
from PIL import Image
import pickle

In [2]:
#load cascade
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_alt2.xml')
recognizer = cv2.face.LBPHFaceRecognizer_create()

In [3]:
# 지금 내 코드 파일
BASE_DIR = os.path.dirname(os.path.abspath('/Users/dayoung/Desktop/실습파일_깃허브로 이동예정/MTCNN-Mosaic-main/mtcnn_이것저것 시도중_1.ipynb'))
# 이미지 경로
image_dir = os.path.join(BASE_DIR, "images")

In [4]:
current_id = 0
label_ids = {}
y_labels = []
x_train = []

In [5]:
# 이미지 경로랑 이름, label 다 print
for root, dirs, files in os.walk(image_dir):
    for file in files:
        if file.endswith("jpg") or file.endswith("jpeg"):
            path = os.path.join(root, file)
            label = os.path.basename(root).replace(" ", "-").lower()
            #print(label, path)
            
            if not label in label_ids:
                label_ids[label] = current_id
                current_id += 1
            id_ = label_ids[label]
            print(label_ids)
                
            
            # y_labels.append(label) # some number
            # x_train.append(path) # verify this image, turn into a numpy array, GRAY
            
            pil_image = Image.open(path).convert("L") #gray scale
            size = (550, 550)
            final_image = pil_image.resize(size, Image.ANTIALIAS)
            image_array = np.array(pil_image, "uint8")
            #print(image_array)
            faces = face_cascade.detectMultiScale(image_array, scaleFactor=1.5, minNeighbors=5)
            
            for (x,y,w,h) in faces:
                roi = image_array[y:y+h, x:x+w]
                #roi에 얼굴 좌표 넣는다.
                x_train.append(roi)
                y_labels.append(id_)
                
#print(y_labels)
#print(x_train)

with open("labels.pickle", 'wb') as f:
    pickle.dump(label_ids, f)

#Train OpenCV
recognizer.train(x_train, np.array(y_labels))
recognizer.save("trainner.yml")
            

{'images': 0}
{'images': 0}
{'images': 0}
{'images': 0}


In [6]:
pil_image = Image.open(path).convert("L") #gray scale
image_array = np.array(pil_image, "uint8")
print(image_array)

[[116 120 120 ... 248 248 248]
 [116 117 117 ... 248 248 248]
 [119 117 116 ... 248 248 248]
 ...
 [209 208 209 ... 235 230 225]
 [219 214 214 ... 237 232 226]
 [214 207 209 ... 238 234 229]]
